### ISSUE TITLE
FFL: CMS does not publish changes.

### ISSUE THREAD

**Issue by tsepot** [universalcore/unicore#67]
Please note that when making changes on the FFL CMS, After I have save and selected the "Publish now" No changes happen on the front end and when you refresh the CMS the notification "You have 23 outstanding changes. Publish now" is returned and the number of changes have added cumulate. 
![screen shot 2014-10-12 at 1 23 11 pm](https://cloud.githubusercontent.com/assets/8982805/4605901/f237c076-5202-11e4-97b5-e5d4c4848e68.png)

**Comment by miltontony** [comment]
@smn it looks like on PROD, the number of open files is an issue again..will investigate in the morning.

**Comment by miltontony** [comment]
```
[2014-10-12 19:17:34,191: ERROR/MainProcess] Task cms.tasks.fastforward[08b9f571-be75-40ec-ad51-cd384e5f5f11] raised unexpected: OSError("/var/praekelt/unicore-cms-mama/unicore_cms_mama_tanzania/.git: Could not open '/var/praekelt/unicore-cms-mama/unicore_cms_mama_tanzania/.git/config': Too many open files",)
Traceback (most recent call last):
  File "/var/praekelt/python/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/praekelt/python/local/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/praekelt/python/local/lib/python2.7/site-packages/cms/tasks.py", line 7, in fastforward
    repo = utils.CmsRepo.read(repo_path)
  File "/var/praekelt/python/local/lib/python2.7/site-packages/cms/utils.py", line 175, in read
    repo = cls(pygit2.Repository(repo_path))
  File "/var/praekelt/python/local/lib/python2.7/site-packages/pygit2/repository.py", line 47, in __init__
    super(Repository, self).__init__(*args, **kwargs)
OSError: /var/praekelt/unicore-cms-mama/unicore_cms_mama_tanzania/.git: Could not open '/var/praekelt/unicore-cms-mama/unicore_cms_mama_tanzania/.git/config': Too many open files
```

**Comment by smn** [comment]
Is production running the latest version?

**Comment by miltontony** [comment]
@smn It looks like gitpython is not going to solve this problem either. This problem is currently an [open issue](https://github.com/gitpython-developers/GitPython/issues/60) on gitpython too

**Comment by smn** [comment]
https://github.com/gitpython-developers/GitPython/issues/60#issuecomment-23652865 is a workaround but terribly ugly.

**Comment by miltontony** [comment]
Resolved by switch to EG/ES
